name: PipelineWorkflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build:
    name: Azure Pipelines
    runs-on: ubuntu-latest
    steps:
      - name: azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-organization-url: https://dev.azure.com/HimanshuSharma1304/Application%20project
          azure-pipeline-name: 'fitness_app2'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
          
    

